"""Initial migration with all tables

Revision ID: ebf54c94b9ea
Revises: 
Create Date: 2025-09-17 23:58:42.532557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf54c94b9ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_contactos_user_id'))
        batch_op.create_index(batch_op.f('ix_contactos_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('contactos_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('contactos_user_id_fkey'), 'users', ['usuario_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_contactos_user_id'))
        batch_op.create_index(batch_op.f('ix_contactos_user_id'), ['usuario_id'], unique=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
